`ifndef AHB_IF_INCLUDED_
`define AHB_IF_INCLUDED_
import uvm_pkg::*;
import ahb_global_pkg::*;
`include "uvm_macros.svh"
// 1. THÊM PARAMETER VÀO ĐÂY ĐỂ KHẮC PHỤC LỖI "UNEXPECTED IDENTIFIER"
interface ahb_if(input clk, input resetn);

    // signal generate from mananger
    logic [ADDR_WIDTH-1 : 0]    haddr;
    logic [2:0]                 hburst;
    logic                       hmastlock;
    logic [3:0]                 hprot;
    logic [2:0]                 hsize;
    logic                       hnonsec;
    logic                       hexcl;
    logic [3:0]                 hmaster;
    logic [1:0]                 htrans;
    logic [DATA_WIDTH-1:0]      hwdata;
    logic [HWSTRB-1:0]          hwstrb;
    logic                       hwrite;

    // singal generate by subordinate
    logic [DATA_WIDTH-1:0]      hrdata;
    logic                       hreadyout;
    logic                       hresp;
    logic                       hexokay;

    //signal generated by decoder
    logic                       hsel;

    //signal generated by multiplexor, if 
    logic                       hready;

    property signal_always_valid;
        @(posedge clk) disable iff(!resetn) 
        (!$isunknown(htrans)) && (!$isunknown(haddr)) && (!$isunknown(hmastlock)) && (!$isunknown(hreadyout)) && (!$isunknown(hresp));
    endproperty : signal_always_valid
    SIGNAL_ALWAYS_VALID : assert property (signal_always_valid);

    property signal_valid_when_htrans_not_IDLE;
        @(posedge clk) disable iff(!resetn)
        (htrans != 2'b00) |-> (!$isunknown(hburst)) && (!$isunknown(hprot)) && (!$isunknown(hsize)) && (!$isunknown(hnonsec)) && (!$isunknown(hexcl)) && (!$isunknown(hmaster))
                            && (!$isunknown(hwrite));
    endproperty : signal_valid_when_htrans_not_IDLE
    SIGNAL_VALID_HTRANS_NOT_IDLE : assert property (signal_valid_when_htrans_not_IDLE);

    property valid_in_write_data_phase;
        @(posedge clk) disable iff(!resetn)
        ((hready == 1) && (hresp == 0) && (hwrite == 1)) |->  (!$isunknown(hexokay));
    endproperty : valid_in_write_data_phase
    SIGNAL_VALID_WRITE_DATA_PHASE : assert property (valid_in_write_data_phase);

    property valid_in_read_data_phase;
        @(posedge clk) disable iff(!resetn)
        ((hready == 1) && (hresp == 0) && (hwrite == 0)) |->  (!$isunknown(hrdata)) && (!$isunknown(hexokay));
    endproperty : valid_in_read_data_phase
    SIGNAL_VALID_READ_DATA_PHASE : assert property (valid_in_read_data_phase);

    property p_hexokay_with_ready;
        @(posedge clk) disable iff(!resetn)
        hexokay == HEXOKAY_PASS |-> hreadyout == 1;
    endproperty : p_hexokay_with_ready
    a_hexokay_with_ready : assert property (p_hexokay_with_ready);

     property p_hexokay_no_hresp_error;
        @(posedge clk) disable iff (!resetn)
        hexokay == 1 |-> (hresp == 1'b0); 
    endproperty : p_hexokay_no_hresp_error
    a_hexokay_no_hresp_error : assert property(p_hexokay_no_hresp_error);
    property p_htrans_stable_during_wait;
        @(posedge clk) disable iff (!resetn)
        // 4. SỬA LỖI TYPO: heady -> hready
        (!$past(hready == 1)) |-> 
            (
                ($past(htrans) == 2'b00 && (htrans == 2'b00 || htrans == 2'b10)) ||
                ($past(htrans) == 2'b01 && $past(hburst) == 3'b001) ||
                ($past(htrans) == 2'b01 && $past(hburst) != 3'b001 && (htrans == 2'b01 || htrans == 2'b11)) ||
                  
                ($past(htrans) == 2'b10 && htrans == 2'b10) ||
                ($past(htrans) == 2'b11 && htrans == 2'b11)
            );
    endproperty
    a_htrans_stable_during_wait: assert property(p_htrans_stable_during_wait);

    property p_hwdata_stable_during_wait;
        @(posedge clk) disable iff (!resetn)
        (hwrite && !$past(hready)) |-> (hwdata == $past(hwdata));
    endproperty
    a_hwdata_stable: assert property(p_hwdata_stable_during_wait);

    property p_error_response_SEQ;
        @(posedge clk) disable iff (!resetn)
        (hresp == 1'b1 && hreadyout == 1'b0) |=> (hresp == 1'b1 && hreadyout == 1'b1);
    endproperty
    a_error_response_SEQ: assert property(p_error_response_SEQ);

    property p_error_response_start_valid;
        @(posedge clk) disable iff (!resetn)
        (hresp == 1'b1 && hreadyout == 1'b1) |-> ($past(hresp) == 1'b1 && $past(hreadyout) == 1'b0);
    endproperty
    a_error_response_start: assert property(p_error_response_start_valid);

     property p_last_burst_single_not_be_BUSY;
         @(posedge clk) disable iff(!resetn)
        (hburst == 3'b000 && hready) |=> (htrans != 2'b01);
    endproperty
    a_last_burst_single_not_be_BUSY : assert property(p_last_burst_single_not_be_BUSY);
    
    property p_locked_transfer_same_addr;
        @(posedge clk) disable iff(!resetn)
        ($past(hmastlock) == 1'b1 && hmastlock == 1'b1) |-> (haddr[31:10] == $past(haddr[31:10]));  
    endproperty
    a_locked_transfer_same_addr : assert property(p_locked_transfer_same_addr);
    initial begin
       $assertoff(0,SIGNAL_ALWAYS_VALID);
       $assertoff(0,SIGNAL_VALID_HTRANS_NOT_IDLE);
        wait(resetn == 0);
        wait(resetn == 1);
       $asserton(0,SIGNAL_ALWAYS_VALID);
       $asserton(0,SIGNAL_VALID_HTRANS_NOT_IDLE);        
        
    end
endinterface : ahb_if
`endif